# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created: Tue Jul 10 19:00:30 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(926, 682)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textEditQuery = Qsci.QsciScintilla(self.centralwidget)
        self.textEditQuery.setToolTip(_fromUtf8(""))
        self.textEditQuery.setWhatsThis(_fromUtf8(""))
        self.textEditQuery.setObjectName(_fromUtf8("textEditQuery"))
        self.gridLayout.addWidget(self.textEditQuery, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuQuery = QtGui.QMenu(self.menubar)
        self.menuQuery.setObjectName(_fromUtf8("menuQuery"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuWindows = QtGui.QMenu(self.menubar)
        self.menuWindows.setObjectName(_fromUtf8("menuWindows"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidgetDataOutput = QtGui.QDockWidget(MainWindow)
        self.dockWidgetDataOutput.setObjectName(_fromUtf8("dockWidgetDataOutput"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tableViewDataOutput = QtGui.QTableView(self.dockWidgetContents)
        self.tableViewDataOutput.setObjectName(_fromUtf8("tableViewDataOutput"))
        self.gridLayout_3.addWidget(self.tableViewDataOutput, 0, 0, 1, 1)
        self.dockWidgetDataOutput.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetDataOutput)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetMessages = QtGui.QDockWidget(MainWindow)
        self.dockWidgetMessages.setObjectName(_fromUtf8("dockWidgetMessages"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.messagesBrowser = QtGui.QTextBrowser(self.dockWidgetContents_2)
        self.messagesBrowser.setObjectName(_fromUtf8("messagesBrowser"))
        self.gridLayout_4.addWidget(self.messagesBrowser, 0, 0, 1, 1)
        self.dockWidgetMessages.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetMessages)
        self.dockWidgetDatabaseLayout = QtGui.QDockWidget(MainWindow)
        self.dockWidgetDatabaseLayout.setObjectName(_fromUtf8("dockWidgetDatabaseLayout"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.treeWidgetDatabaseLayout = QtGui.QTreeWidget(self.dockWidgetContents_5)
        self.treeWidgetDatabaseLayout.setObjectName(_fromUtf8("treeWidgetDatabaseLayout"))
        self.treeWidgetDatabaseLayout.headerItem().setText(0, _fromUtf8("Database"))
        self.gridLayout_2.addWidget(self.treeWidgetDatabaseLayout, 0, 0, 1, 1)
        self.dockWidgetDatabaseLayout.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetDatabaseLayout)
        self.dockWidgetDocumentation = QtGui.QDockWidget(MainWindow)
        self.dockWidgetDocumentation.setObjectName(_fromUtf8("dockWidgetDocumentation"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.webViewDocumentation = QtWebKit.QWebView(self.dockWidgetContents_3)
        self.webViewDocumentation.setUrl(QtCore.QUrl(_fromUtf8("http://www.postgresql.org/docs/8.4/interactive/index.html")))
        self.webViewDocumentation.setObjectName(_fromUtf8("webViewDocumentation"))
        self.gridLayout_5.addWidget(self.webViewDocumentation, 1, 0, 1, 7)
        self.LineEditDocumentationUrl = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.LineEditDocumentationUrl.setObjectName(_fromUtf8("LineEditDocumentationUrl"))
        self.gridLayout_5.addWidget(self.LineEditDocumentationUrl, 0, 5, 1, 1)
        self.progressBarDocumentation = QtGui.QProgressBar(self.dockWidgetContents_3)
        self.progressBarDocumentation.setProperty("value", 24)
        self.progressBarDocumentation.setObjectName(_fromUtf8("progressBarDocumentation"))
        self.gridLayout_5.addWidget(self.progressBarDocumentation, 2, 0, 1, 7)
        self.toolButtonStop = QtGui.QToolButton(self.dockWidgetContents_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/images/Stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonStop.setIcon(icon)
        self.toolButtonStop.setObjectName(_fromUtf8("toolButtonStop"))
        self.gridLayout_5.addWidget(self.toolButtonStop, 0, 4, 1, 1)
        self.toolButtonReload = QtGui.QToolButton(self.dockWidgetContents_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/images/Refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonReload.setIcon(icon1)
        self.toolButtonReload.setObjectName(_fromUtf8("toolButtonReload"))
        self.gridLayout_5.addWidget(self.toolButtonReload, 0, 3, 1, 1)
        self.toolButtonBackward = QtGui.QToolButton(self.dockWidgetContents_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/images/Undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonBackward.setIcon(icon2)
        self.toolButtonBackward.setObjectName(_fromUtf8("toolButtonBackward"))
        self.gridLayout_5.addWidget(self.toolButtonBackward, 0, 1, 1, 1)
        self.toolButtonForward = QtGui.QToolButton(self.dockWidgetContents_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/images/Redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonForward.setIcon(icon3)
        self.toolButtonForward.setObjectName(_fromUtf8("toolButtonForward"))
        self.gridLayout_5.addWidget(self.toolButtonForward, 0, 2, 1, 1)
        self.toolButtonGo = QtGui.QToolButton(self.dockWidgetContents_3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/images/Execute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGo.setIcon(icon4)
        self.toolButtonGo.setObjectName(_fromUtf8("toolButtonGo"))
        self.gridLayout_5.addWidget(self.toolButtonGo, 0, 6, 1, 1)
        self.dockWidgetDocumentation.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetDocumentation)
        self.actionExecute = QtGui.QAction(MainWindow)
        self.actionExecute.setObjectName(_fromUtf8("actionExecute"))
        self.actionExplainAnalyze = QtGui.QAction(MainWindow)
        self.actionExplainAnalyze.setCheckable(True)
        self.actionExplainAnalyze.setChecked(True)
        self.actionExplainAnalyze.setObjectName(_fromUtf8("actionExplainAnalyze"))
        self.actionExplain = QtGui.QAction(MainWindow)
        self.actionExplain.setObjectName(_fromUtf8("actionExplain"))
        self.actionFormat = QtGui.QAction(MainWindow)
        self.actionFormat.setObjectName(_fromUtf8("actionFormat"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionDatabaseLayout = QtGui.QAction(MainWindow)
        self.actionDatabaseLayout.setCheckable(True)
        self.actionDatabaseLayout.setObjectName(_fromUtf8("actionDatabaseLayout"))
        self.actionDataOutput = QtGui.QAction(MainWindow)
        self.actionDataOutput.setCheckable(True)
        self.actionDataOutput.setObjectName(_fromUtf8("actionDataOutput"))
        self.actionMessages = QtGui.QAction(MainWindow)
        self.actionMessages.setCheckable(True)
        self.actionMessages.setObjectName(_fromUtf8("actionMessages"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setCheckable(True)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionUnindent = QtGui.QAction(MainWindow)
        self.actionUnindent.setObjectName(_fromUtf8("actionUnindent"))
        self.actionIndent = QtGui.QAction(MainWindow)
        self.actionIndent.setObjectName(_fromUtf8("actionIndent"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionComment = QtGui.QAction(MainWindow)
        self.actionComment.setObjectName(_fromUtf8("actionComment"))
        self.actionUncomment = QtGui.QAction(MainWindow)
        self.actionUncomment.setObjectName(_fromUtf8("actionUncomment"))
        self.menuQuery.addAction(self.actionExecute)
        self.menuQuery.addAction(self.actionExplainAnalyze)
        self.menuQuery.addAction(self.actionExplain)
        self.menuQuery.addAction(self.actionFormat)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuWindows.addAction(self.actionDatabaseLayout)
        self.menuWindows.addAction(self.actionDataOutput)
        self.menuWindows.addAction(self.actionMessages)
        self.menuWindows.addAction(self.actionDocumentation)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionComment)
        self.menuEdit.addAction(self.actionUncomment)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionIndent)
        self.menuEdit.addAction(self.actionUnindent)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuQuery.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.toolBar.addAction(self.actionExecute)
        self.toolBar.addAction(self.actionExplainAnalyze)
        self.toolBar.addAction(self.actionExplain)
        self.toolBar.addAction(self.actionFormat)
        self.toolBar.addAction(self.actionDocumentation)
        self.toolBar.addAction(self.actionMessages)
        self.toolBar.addAction(self.actionDataOutput)
        self.toolBar.addAction(self.actionDatabaseLayout)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.webViewDocumentation, QtCore.SIGNAL(_fromUtf8("loadProgress(int)")), self.progressBarDocumentation.setValue)
        QtCore.QObject.connect(self.toolButtonStop, QtCore.SIGNAL(_fromUtf8("pressed()")), self.webViewDocumentation.stop)
        QtCore.QObject.connect(self.toolButtonReload, QtCore.SIGNAL(_fromUtf8("pressed()")), self.webViewDocumentation.reload)
        QtCore.QObject.connect(self.toolButtonForward, QtCore.SIGNAL(_fromUtf8("pressed()")), self.webViewDocumentation.forward)
        QtCore.QObject.connect(self.toolButtonBackward, QtCore.SIGNAL(_fromUtf8("pressed()")), self.webViewDocumentation.back)
        QtCore.QObject.connect(self.actionMessages, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidgetMessages.setVisible)
        QtCore.QObject.connect(self.actionDatabaseLayout, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidgetDatabaseLayout.setVisible)
        QtCore.QObject.connect(self.actionDocumentation, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidgetDocumentation.setVisible)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.actionDataOutput, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidgetDataOutput.setVisible)
        QtCore.QObject.connect(self.dockWidgetMessages, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionMessages.setChecked)
        QtCore.QObject.connect(self.dockWidgetDataOutput, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDataOutput.setChecked)
        QtCore.QObject.connect(self.dockWidgetDocumentation, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDocumentation.setChecked)
        QtCore.QObject.connect(self.dockWidgetDatabaseLayout, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDatabaseLayout.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QtQuery", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuery.setTitle(QtGui.QApplication.translate("MainWindow", "Query", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindows.setTitle(QtGui.QApplication.translate("MainWindow", "Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetDataOutput.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Data Output", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Main Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetMessages.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetDatabaseLayout.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Database Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDatabaseLayout.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetDocumentation.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonReload.setText(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonBackward.setText(QtGui.QApplication.translate("MainWindow", "Backward", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonForward.setText(QtGui.QApplication.translate("MainWindow", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGo.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExecute.setText(QtGui.QApplication.translate("MainWindow", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExecute.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExplainAnalyze.setText(QtGui.QApplication.translate("MainWindow", "Explain: Analyze", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExplain.setText(QtGui.QApplication.translate("MainWindow", "Explain", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExplain.setShortcut(QtGui.QApplication.translate("MainWindow", "F7", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFormat.setText(QtGui.QApplication.translate("MainWindow", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFormat.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatabaseLayout.setText(QtGui.QApplication.translate("MainWindow", "Database Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDataOutput.setText(QtGui.QApplication.translate("MainWindow", "Data Output", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMessages.setText(QtGui.QApplication.translate("MainWindow", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnindent.setText(QtGui.QApplication.translate("MainWindow", "Unindent", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIndent.setText(QtGui.QApplication.translate("MainWindow", "Indent", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment.setText(QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComment.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+/", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUncomment.setText(QtGui.QApplication.translate("MainWindow", "Uncomment", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUncomment.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+?", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
from PyQt4 import Qsci
import resources_rc
