# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created: Thu Jul 24 04:15:28 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsTabWidget(object):
    def setupUi(self, SettingsTabWidget):
        SettingsTabWidget.setObjectName(_fromUtf8("SettingsTabWidget"))
        SettingsTabWidget.resize(778, 530)
        self.tabDatabases = QtGui.QWidget()
        self.tabDatabases.setObjectName(_fromUtf8("tabDatabases"))
        self.gridLayout = QtGui.QGridLayout(self.tabDatabases)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QtGui.QWidget(self.tabDatabases)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.splitter = QtGui.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.gridLayoutWidget = QtGui.QWidget(self.splitter)
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayoutDatabases = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutDatabases.setMargin(0)
        self.gridLayoutDatabases.setObjectName(_fromUtf8("gridLayoutDatabases"))
        self.databasesTreeWidget = QtGui.QTreeWidget(self.gridLayoutWidget)
        self.databasesTreeWidget.setMinimumSize(QtCore.QSize(410, 0))
        self.databasesTreeWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.databasesTreeWidget.setObjectName(_fromUtf8("databasesTreeWidget"))
        self.gridLayoutDatabases.addWidget(self.databasesTreeWidget, 0, 0, 1, 3)
        self.buttonDelete = QtGui.QToolButton(self.gridLayoutWidget)
        self.buttonDelete.setEnabled(False)
        self.buttonDelete.setObjectName(_fromUtf8("buttonDelete"))
        self.gridLayoutDatabases.addWidget(self.buttonDelete, 1, 0, 1, 1)
        self.buttonAdd = QtGui.QToolButton(self.gridLayoutWidget)
        self.buttonAdd.setObjectName(_fromUtf8("buttonAdd"))
        self.gridLayoutDatabases.addWidget(self.buttonAdd, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutDatabases.addItem(spacerItem, 1, 2, 1, 1)
        self.groupBoxDatabase = QtGui.QGroupBox(self.splitter)
        self.groupBoxDatabase.setObjectName(_fromUtf8("groupBoxDatabase"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxDatabase)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.spinBoxConnectTimeout = QtGui.QSpinBox(self.groupBoxDatabase)
        self.spinBoxConnectTimeout.setMinimum(1)
        self.spinBoxConnectTimeout.setMaximum(60)
        self.spinBoxConnectTimeout.setObjectName(_fromUtf8("spinBoxConnectTimeout"))
        self.gridLayout_2.addWidget(self.spinBoxConnectTimeout, 5, 1, 1, 1)
        self.labelRequireSSL = QtGui.QLabel(self.groupBoxDatabase)
        self.labelRequireSSL.setObjectName(_fromUtf8("labelRequireSSL"))
        self.gridLayout_2.addWidget(self.labelRequireSSL, 6, 0, 1, 1)
        self.plainTextEditService = QtGui.QPlainTextEdit(self.groupBoxDatabase)
        self.plainTextEditService.setObjectName(_fromUtf8("plainTextEditService"))
        self.gridLayout_2.addWidget(self.plainTextEditService, 8, 1, 1, 1)
        self.lineEditHost = QtGui.QLineEdit(self.groupBoxDatabase)
        self.lineEditHost.setObjectName(_fromUtf8("lineEditHost"))
        self.gridLayout_2.addWidget(self.lineEditHost, 1, 1, 1, 1)
        self.labelOptions = QtGui.QLabel(self.groupBoxDatabase)
        self.labelOptions.setObjectName(_fromUtf8("labelOptions"))
        self.gridLayout_2.addWidget(self.labelOptions, 7, 0, 1, 1)
        self.labelConnectTimeout = QtGui.QLabel(self.groupBoxDatabase)
        self.labelConnectTimeout.setObjectName(_fromUtf8("labelConnectTimeout"))
        self.gridLayout_2.addWidget(self.labelConnectTimeout, 5, 0, 1, 1)
        self.labelUser = QtGui.QLabel(self.groupBoxDatabase)
        self.labelUser.setObjectName(_fromUtf8("labelUser"))
        self.gridLayout_2.addWidget(self.labelUser, 3, 0, 1, 1)
        self.labelName = QtGui.QLabel(self.groupBoxDatabase)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.gridLayout_2.addWidget(self.labelName, 0, 0, 1, 1)
        self.lineEditPort = QtGui.QLineEdit(self.groupBoxDatabase)
        self.lineEditPort.setObjectName(_fromUtf8("lineEditPort"))
        self.gridLayout_2.addWidget(self.lineEditPort, 2, 1, 1, 1)
        self.labelHost = QtGui.QLabel(self.groupBoxDatabase)
        self.labelHost.setObjectName(_fromUtf8("labelHost"))
        self.gridLayout_2.addWidget(self.labelHost, 1, 0, 1, 1)
        self.lineEditName = QtGui.QLineEdit(self.groupBoxDatabase)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.gridLayout_2.addWidget(self.lineEditName, 0, 1, 1, 1)
        self.labelPass = QtGui.QLabel(self.groupBoxDatabase)
        self.labelPass.setObjectName(_fromUtf8("labelPass"))
        self.gridLayout_2.addWidget(self.labelPass, 4, 0, 1, 1)
        self.lineEditPass = QtGui.QLineEdit(self.groupBoxDatabase)
        self.lineEditPass.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditPass.setObjectName(_fromUtf8("lineEditPass"))
        self.gridLayout_2.addWidget(self.lineEditPass, 4, 1, 1, 1)
        self.lineEditUser = QtGui.QLineEdit(self.groupBoxDatabase)
        self.lineEditUser.setObjectName(_fromUtf8("lineEditUser"))
        self.gridLayout_2.addWidget(self.lineEditUser, 3, 1, 1, 1)
        self.labelService = QtGui.QLabel(self.groupBoxDatabase)
        self.labelService.setObjectName(_fromUtf8("labelService"))
        self.gridLayout_2.addWidget(self.labelService, 8, 0, 1, 1)
        self.checkBoxRequireSSL = QtGui.QCheckBox(self.groupBoxDatabase)
        self.checkBoxRequireSSL.setText(_fromUtf8(""))
        self.checkBoxRequireSSL.setObjectName(_fromUtf8("checkBoxRequireSSL"))
        self.gridLayout_2.addWidget(self.checkBoxRequireSSL, 6, 1, 1, 1)
        self.labelPort = QtGui.QLabel(self.groupBoxDatabase)
        self.labelPort.setObjectName(_fromUtf8("labelPort"))
        self.gridLayout_2.addWidget(self.labelPort, 2, 0, 1, 1)
        self.plainTextEditOptions = QtGui.QPlainTextEdit(self.groupBoxDatabase)
        self.plainTextEditOptions.setObjectName(_fromUtf8("plainTextEditOptions"))
        self.gridLayout_2.addWidget(self.plainTextEditOptions, 7, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonTest = QtGui.QToolButton(self.groupBoxDatabase)
        self.buttonTest.setObjectName(_fromUtf8("buttonTest"))
        self.horizontalLayout_2.addWidget(self.buttonTest)
        self.labelTestOutput = QtGui.QLabel(self.groupBoxDatabase)
        self.labelTestOutput.setText(_fromUtf8(""))
        self.labelTestOutput.setObjectName(_fromUtf8("labelTestOutput"))
        self.horizontalLayout_2.addWidget(self.labelTestOutput)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 9, 0, 1, 2)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        SettingsTabWidget.addTab(self.tabDatabases, _fromUtf8(""))
        self.labelRequireSSL.setBuddy(self.checkBoxRequireSSL)
        self.labelOptions.setBuddy(self.plainTextEditOptions)
        self.labelConnectTimeout.setBuddy(self.spinBoxConnectTimeout)
        self.labelUser.setBuddy(self.lineEditUser)
        self.labelName.setBuddy(self.lineEditName)
        self.labelHost.setBuddy(self.lineEditHost)
        self.labelPass.setBuddy(self.lineEditPass)
        self.labelService.setBuddy(self.plainTextEditService)
        self.labelPort.setBuddy(self.lineEditPort)

        self.retranslateUi(SettingsTabWidget)
        SettingsTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonTest, QtCore.SIGNAL(_fromUtf8("clicked()")), self.labelTestOutput.clear)
        QtCore.QMetaObject.connectSlotsByName(SettingsTabWidget)
        SettingsTabWidget.setTabOrder(self.databasesTreeWidget, self.buttonDelete)
        SettingsTabWidget.setTabOrder(self.buttonDelete, self.buttonAdd)
        SettingsTabWidget.setTabOrder(self.buttonAdd, self.lineEditName)
        SettingsTabWidget.setTabOrder(self.lineEditName, self.lineEditHost)
        SettingsTabWidget.setTabOrder(self.lineEditHost, self.lineEditPort)
        SettingsTabWidget.setTabOrder(self.lineEditPort, self.lineEditUser)
        SettingsTabWidget.setTabOrder(self.lineEditUser, self.lineEditPass)
        SettingsTabWidget.setTabOrder(self.lineEditPass, self.spinBoxConnectTimeout)
        SettingsTabWidget.setTabOrder(self.spinBoxConnectTimeout, self.checkBoxRequireSSL)
        SettingsTabWidget.setTabOrder(self.checkBoxRequireSSL, self.plainTextEditOptions)
        SettingsTabWidget.setTabOrder(self.plainTextEditOptions, self.plainTextEditService)

    def retranslateUi(self, SettingsTabWidget):
        SettingsTabWidget.setWindowTitle(_translate("SettingsTabWidget", "Settings", None))
        self.databasesTreeWidget.headerItem().setText(0, _translate("SettingsTabWidget", "Name", None))
        self.databasesTreeWidget.headerItem().setText(1, _translate("SettingsTabWidget", "Host", None))
        self.databasesTreeWidget.headerItem().setText(2, _translate("SettingsTabWidget", "Port", None))
        self.databasesTreeWidget.headerItem().setText(3, _translate("SettingsTabWidget", "User", None))
        self.buttonDelete.setText(_translate("SettingsTabWidget", "-", None))
        self.buttonAdd.setText(_translate("SettingsTabWidget", "+", None))
        self.groupBoxDatabase.setTitle(_translate("SettingsTabWidget", "Database", None))
        self.labelRequireSSL.setText(_translate("SettingsTabWidget", "Require SSL", None))
        self.labelOptions.setText(_translate("SettingsTabWidget", "Options", None))
        self.labelConnectTimeout.setText(_translate("SettingsTabWidget", "Connect Timeout", None))
        self.labelUser.setText(_translate("SettingsTabWidget", "User", None))
        self.labelName.setText(_translate("SettingsTabWidget", "Name", None))
        self.labelHost.setText(_translate("SettingsTabWidget", "Host", None))
        self.labelPass.setText(_translate("SettingsTabWidget", "Pass", None))
        self.labelService.setText(_translate("SettingsTabWidget", "Service", None))
        self.labelPort.setText(_translate("SettingsTabWidget", "Port", None))
        self.buttonTest.setText(_translate("SettingsTabWidget", "Test settings", None))
        SettingsTabWidget.setTabText(SettingsTabWidget.indexOf(self.tabDatabases), _translate("SettingsTabWidget", "Databases", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SettingsTabWidget = QtGui.QTabWidget()
    ui = Ui_SettingsTabWidget()
    ui.setupUi(SettingsTabWidget)
    SettingsTabWidget.show()
    sys.exit(app.exec_())

